
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/kimseanbun/Downloads/Tkinter-Designer-master/build/assets/frame8")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window1 = Tk()
window1.title('Dashboard')
window1.geometry("900x600")
window1.configure(bg = "#F3FDF6")


canvas = Canvas(
    window1,
    bg = "#F3FDF6",
    height = 600,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    241.0,
    106.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    161.0,
    445.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    521.0,
    444.0,
    image=image_image_3
)

canvas.create_rectangle(
    91.0,
    173.0,
    431.0,
    343.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    450.0,
    173.0,
    790.0,
    343.0,
    fill="#FFFFFF",
    outline="")

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    706.0,
    234.0,
    image=image_image_4
)

canvas.create_rectangle(
    518.0,
    282.0,
    720.0,
    284.0,
    fill="#D9D9D9",
    outline="")

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    172.0,
    228.0,
    image=image_image_5
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    528.0,
    229.0,
    image=image_image_6
)
def button1_click():
    print("button_1 clicked")
    window1.destroy()
    import DeleteStudent as DeleteStudent


button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=button1_click,
    relief="flat"
)
button_1.place(
    x=260.0,
    y=299.0,
    width=70.0,
    height=20.0
)

def button2_click():
    print("button_2 clicked")
    window1.destroy()
    import StudentRegistration as StudentRegistration


button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=button2_click ,
    relief="flat"
)
button_2.place(
    x=145.0,
    y=299.0,
    width=93.0,
    height=20.0
)

def button3_click():
    print("button_3 clicked")
    window1.destroy()
    import DeleteBook as DeleteBook
    
button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=button3_click,
    relief="flat"
)
button_3.place(
    x=617.0,
    y=300.0,
    width=70.0,
    height=20.0
)

def button4_click():
    print("button_4 clicked")
    window1.destroy()
    import BookRegistration as BookRegistration

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=button4_click,
    relief="flat"
)
button_4.place(
    x=502.0,
    y=300.0,
    width=93.0,
    height=20.0
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    326.0,
    233.0,
    image=image_image_7
)

canvas.create_rectangle(
    159.0,
    281.0,
    361.0,
    283.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    90.0,
    368.0,
    430.0,
    538.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    450.0,
    367.0,
    790.0,
    537.0,
    fill="#FFFFFF",
    outline="")

def button5_click():
    print("button_5 clicked")
    window1.destroy()
    import Return as Return

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=button5_click,
    relief="flat"
)
button_5.place(
    x=260.0,
    y=494.0,
    width=70.0,
    height=20.0
)

def button6_click():
    print("button_6 clicked")
    window1.destroy()
    import CheckOut as CheckOut

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=button6_click,
    relief="flat"
)
button_6.place(
    x=145.0,
    y=494.0,
    width=93.0,
    height=20.0
)
def button7_click():
    print("button_7 clicked")
    window1.destroy()
    import Search as Search

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=button7_click,
    relief="flat"
)
button_7.place(
    x=505.0,
    y=493.0,
    width=77.0,
    height=20.0
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    312.0,
    428.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    703.0,
    427.0,
    image=image_image_9
)

canvas.create_rectangle(
    159.0,
    476.0,
    361.0,
    478.0,
    fill="#D9D9D9",
    outline="")

canvas.create_rectangle(
    519.0,
    475.0,
    721.0,
    477.0,
    fill="#D9D9D9",
    outline="")

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    743.0,
    100.0,
    image=image_image_10
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    177.0,
    428.0,
    image=image_image_11
)

image_image_12 = PhotoImage(
    file=relative_to_assets("image_12.png"))
image_12 = canvas.create_image(
    525.0,
    423.0,
    image=image_image_12
)
window1.resizable(False, False)
window1.mainloop()
