
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/kimseanbun/Downloads/Tkinter-Designer-master/build/assets/frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()
window.title('DeleteBook')
window.geometry("900x600")
window.configure(bg = "#F3FDF6")


canvas = Canvas(
    window,
    bg = "#F3FDF6",
    height = 600,
    width = 900,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    450.0,
    103.0,
    image=image_image_1
)
def button1_click():
    print("button_1 clicked")
    window.destroy()
    import Dashboard as Dashboard

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=button1_click,
    relief="flat"
)
button_1.place(
    x=135.0,
    y=85.0,
    width=30.0,
    height=30.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    359.0,
    94.0,
    image=image_image_2
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    510.0,
    286.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#E6E6E6",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=339.0,
    y=269.0,
    width=342.0,
    height=33.0
)

canvas.create_text(
    215.0,
    277.0,
    anchor="nw",
    text="Barcode",
    fill="#000000",
    font=("Inter Medium", 17 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    510.0,
    228.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#E6E6E6",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=339.0,
    y=211.0,
    width=342.0,
    height=33.0
)

canvas.create_text(
    215.0,
    219.0,
    anchor="nw",
    text="BookID",
    fill="#000000",
    font=("Inter Medium", 17 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    30.0,
    200.0,
    image=image_image_3
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=215.0,
    y=370.0,
    width=120.0,
    height=35.0
)

canvas.create_text(
    215.0,
    342.0,
    anchor="nw",
    text="*This action cannot be undo",
    fill="#000000",
    font=("Inter ExtraLight", 12 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    685.0,
    100.0,
    image=image_image_4
)
window.resizable(False, False)
window.mainloop()
